idf_component_register(
    SRCS "main.c"
         "src/core/hs_events.c"
         "src/core/hs_actor.c"
         "src/core/settings.c"
         "src/board/board_i2c.c"
         "src/board/board_button.c"
         "src/bt/bt_app_core.c"
         "src/bt/bt_core.c"
         "src/bt/bt_gap.c"
         "src/bt/bt_a2dp.c"
         "src/bt/bt_avrcp.c"
         "src/bt/bt_hfp.c"
         "src/bt/bt_ble.c"
         "src/bt/bt_fastpair.c"
         "src/bt/bt_link_mgr.c"
         "src/bt/bt_eq_service.c"
         "src/bt/bt_ctl_service.c"
         "src/bt/phone_ctl.c"
         "src/audio/audio.c"
         "src/audio/audio_codec.c"
         "src/audio/audio_io.c"
         "src/audio/eq.c"
         "src/audio/sfx.c"
         "src/audio/voice_nr.c"
         "src/audio/wm8960.c"
         "src/sensor/apds9930.c"
         "src/sensor/battery.c"
         "src/display/display.c"
         "src/display/ui_bridge.c"
         "src/display/ui_model.c"
    INCLUDE_DIRS "."
                 "src/core"
                 "src/board"
                 "src/bt"
                 "src/audio"
                 "src/sensor"
                 "src/display"
    PRIV_REQUIRES
        nvs_flash
        esp_driver_i2c
        esp_driver_i2s
        esp_driver_gpio
        esp_driver_spi
        esp_lcd
        esp_ringbuf
        esp_adc
        esp_event
        mbedtls
    REQUIRES
        bt
        esp_timer
        lvgl
        ui
)
