idf_component_register(
    SRCS "main.c"
         "src/core/headset_events.c"
         "src/board/board_i2c.c"
         "src/board/board_button.c"
         "src/bt/bt_app_core.c"
         "src/bt/bt_core.c"
         "src/bt/bt_gap.c"
         "src/bt/bt_a2dp.c"
         "src/bt/bt_avrcp.c"
         "src/bt/bt_hfp.c"
         "src/bt/bt_ble.c"
         "src/bt/bt_fastpair.c"
         "src/bt/bt_link_mgr.c"
         "src/audio/audio.c"
         "src/audio/audio_codec.c"
         "src/audio/audio_io.c"
         "src/audio/voice_nr.c"
         "src/audio/wm8960.c"
         "src/sensor/apds9930.c"
         "src/sensor/battery.c"
    INCLUDE_DIRS "."
                 "src/core"
                 "src/board"
                 "src/bt"
                 "src/audio"
                 "src/sensor"
    PRIV_REQUIRES
        nvs_flash
        esp_driver_i2c
        esp_driver_i2s
        esp_driver_gpio
        esp_ringbuf
        esp_adc
        esp_event
        mbedtls
    REQUIRES
        bt
        esp_timer
)
