list(
  APPEND
  LV_EDITOR_PROJECT_SOURCES
  ${CMAKE_CURRENT_LIST_DIR}/components/base/button_subtle/button_subtle_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/base/button/button_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/base/card/card_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/base/column/column_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/base/container/container_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/base/label/label_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/base/panel/panel_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/base/row/row_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/base/slider/slider_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/cont_slider_toque_b/cont_slider_toque_b_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/cont_slider_toque_c/cont_slider_toque_c_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/cont_slider_toque_d/cont_slider_toque_d_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/cont_slider_toque_e/cont_slider_toque_e_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/cont_slider_toque/cont_slider_toque_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/derived/tile_2/tile_2_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/derived/tile_3/tile_3_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/derived/tile_4/tile_4_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/derived/tile_5/tile_5_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/derived/tile/tile_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_apps_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_bluetooth_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_display_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_galeria_gifs_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_galeria_imagens_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_main_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_main_gif_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_orelhas_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_proximidade_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_settings_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_status_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_vibracall_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/ui_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/ui.c)